#Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. 
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
  external_labels:
      monitor: 'example'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: '/metrics'

  - job_name: 'system_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['system_exporter:2112']
    metrics_path: '/metrics'
